config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :users, only: [:show]

  resources :movies do
    collection do
      get :top_rated_movies
    end
    resources :reviews, except: [:show, :index]
    resources :bookings
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :movie

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.order("created_at DESC")
    @movies = scope
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def top_rated_movies
    #all top rated movies
    @movies = Movie.where('avg_rating > ?', 3)
    # authorize! :read, @movie
  end
  def edit
  end

  def new
    @movie = current_user.movies.build
  end
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :actros, :user_id, :genre, :avatar, :price)
    end

  def scope
    ::Movie.all.includes(:bookings)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<body class="bg-gradient-primary">

<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Create a new Movie!</h1>
            </div>
              <%= form_with(model: movie, local: true, html: { multipart: true, :class=> "user"}) do |form| %>
                <% if movie.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
                    <ul>
                      <% movie.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              <div class="form-group">
                <%= form.label :title %>
                <%= form.text_field :title,  :class=>"form-control form-control-user", :id =>"exampleFirstName", :placeholder => "Movie Title" %>
              </div>
              <div class="form-group">
                <%= form.label :description %>
                <%= form.text_area :description,  :class=>"form-control form-control-user",
                                   :id =>"exampleFirstName", :placeholder => "Place movie's description here ... " %>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= form.label :movie_length %>
                  <%= form.text_field :movie_length, :class=>"form-control form-control-user", :id =>"exampleFirstName", :placeholder => "Movie Length" %>
                </div>
                <div class="col-sm-6">
                  <%= form.label :director %>
                  <%= form.text_field :director, :class=>"form-control form-control-user", :id =>"exampleFirstName", :placeholder => "Movie's director name" %>
                </div>
              </div>
              <div class="form-group">
                <%= form.label :actros %>
                <%= form.text_field :actros, :class=>"form-control form-control-user", :id =>"exampleFirstName", :placeholder => "Movie's actors name" %>
              </div>
              <div class="form-group">
                <%= form.label :price %>
                <%= form.text_field :price, :class=>"form-control form-control-user", :id =>"exampleFirstName", :placeholder => "Movie's ticket's price" %>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= form.label :genre %><br>
                  <%= form.select :genre, ["Select", "Action","Horor","Scifi", "Comedy", "Romantic"], :class=>"form-control form-control-user",
                                  :id =>"exampleFirstName" %>
                </div>

                <div class="col-sm-6">
                  <%= form.label :photo %>
                  <%= form.file_field :avatar %>
                </div>
              </div>
              <a class="btn btn-primary btn-user btn-block">
                <%= form.submit :class => "btn btn-primary btn-user btn-block", :value=> "Create Movie!" %>
              </a>
            <% end %>
            <hr>
            <div class="text-center">
              <% if @movie.id.present? %>
              <%= link_to 'Back to Movie!', @movie %> |
              <% end %>
              <%= link_to 'Back to Home Page!', movies_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
</body>

app/views/movies/edit.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<div class="container-fluid">
  <div class="row">
    <% if !user_signed_in? %>
      <div class="jumbotron">
        <h1>Your Favorite Movies Reviewed</h1>
        <p>Hashtag hoodie mumblecore selfies. Authentic keffiyeh leggings Kickstarter, narwhal jean shorts XOXO Vice Austin cardigan. Organic drinking vinegar freegan pickled.</p>
        <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
      </div>
    <% end %>
  </div>
  <% if !current_user.has_role? :admin %>
    <%= link_to 'Top Rated Movies', top_rated_movies_movies_path, class: "btn btn-success" %><br><br>
  <% end %>
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-3 col-sm-6 col-lg-3 movie-image-style">
          <%= link_to (image_tag movie.avatar.url(:medium), height: '430', width: '350'), movie %>
      </div>
    <% end %>
  </div>
  <br>
  <% if current_user.has_role? :admin %>
    <%= link_to 'Create New Movie', new_movie_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/movies/new.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="container">
    <div class="row">
      <div class="col-md-4">
        <% if !current_user.has_role? :admin %>
          <%= link_to "Book a Ticket!", new_movie_booking_path(@movie, @booking), :class=> "btn btn-primary" %><br><br>
        <% end %>
        <%= image_tag @movie.avatar.url(:medium), width: "300", height: "300" %>
        <div class="star-rating" data-score= <%= @avg_rating %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
            <tr>
              <td><strong>Title:</strong></td>
              <td><%= @movie.title %></td>
            </tr>
            <tr>
              <td><strong>Description:</strong></td>
              <td><%= @movie.description %></td>
            </tr>
            <tr>
              <td><strong>Movie length:</strong></td>
              <td><%= @movie.movie_length %></td>
            </tr>
            <tr>
              <td><strong>Director:</strong></td>
              <td><%= @movie.director %></td>
            </tr>
            <tr>
              <td><strong>Actors:</strong></td>
              <td><%= @movie.actros %></td>
            </tr>
            <tr>
              <td><strong>Genre:</strong></td>
              <td><%= @movie.genre  %></td>
            </tr>
            <tr>
              <td><strong>Price:</strong></td>
              <td>PKR/- <%= @movie.price  %></td>
            </tr>
            <tr>
              <td><strong>User:</strong></td>
              <td><%= @movie.user.full_name %></td>
            </tr>
            </tbody>
          </table>

        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>
        <p><%= @movie.description %></p>
        <% if @reviews.blank? %>
          <h3>No reviews just yet
            <% if !current_user.has_role? :admin %>
              , would you like to add the first!</h3>
              <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
            <% end %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <p>Username: <%= review.user.full_name%>
              <p class="star-rating" data-score= <%= review.rating %> ></p>
              <p><%= review.comment %></p>
              <hr>
            </div>
          <% end %>
        <% end %>
        <% if !current_user.has_role? :admin %>
          <% if @movie.reviews.present? %>
            <%= link_to "Write a Review", new_movie_review_path(@movie), :class=> "btn btn-primary"  %>
          <% end %>
        <% end %>
      </div>
    </div>
      <% if current_user.has_role? :admin %>
        <%= link_to 'Edit Movie!', edit_movie_path(@movie) , :class=> "btn btn-primary" %> |
      <% end %>
      <%= link_to 'Back to Home Page', movies_path, :class=> "btn btn-primary"  %>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {
        $(".star-rating").raty({
            path: '/assets/',
            readOnly: true,
            score: function() {
                return $(this).attr('data-score');
            }
        });
    })
</script>

app/views/movies/top_rated_movies.html.erb
<div class="container-fluid">
  <h1>Top Rated Movies</h1>
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-3 col-sm-6 col-lg-3 movie-image-style">
        <%= link_to (image_tag movie.avatar.url(:medium), height: '430', width: '350'), movie %>
      </div>
    <% end %>
  </div>
  <br>
</div>