config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :users, only: [:show]

  resources :movies do
    collection do
      get :top_rated_movies
    end
    resources :reviews, except: [:show, :index]
    resources :bookings
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    if @review.save
      @review.update_movie_avg_rating(@movie)
      redirect_to @movie
    else
      render 'new'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    params.require(:review).permit(:rating, :comment)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for([@movie, review] , local: true) do |form| %>
      <% if review.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

          <ul>
            <% review.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <div id="star-rating"></div>
      </div>

      <div class="field">
        <%= form.label :comment %>
        <%= form.text_area :comment %>
      </div>

      <div class="field">
        <%= form.hidden_field :user_id, value: current_user.id %>
      </div>

      <div class="field">
        <%= form.hidden_field :movie_id, value: @movie %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>

    <script>
        $('#star-rating').raty({
            path: '/assets/',
            scoreName: 'review[rating]'
        });
    </script>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Editing Review</h1>
    <%= render 'form', review: @review %>
    <%= link_to 'Show', @review %> |
    <%= link_to 'Back', reviews_path %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Review</h1>
    <%= render 'form', review: @review %>
    <%= link_to 'Back', movie_path(@movie) %>
  </div>
</div>